Fix python3 compatibility for sphinx conf.py
In python3, subprocess.check_output() returns a bytearray. We need to
encode this into a string type for 'version' and fix this error:

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/usr/lib/python3/dist-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/rob/proj/git/devicetree-specification/source/conf.py", line 260, in <module>
    if '-' in release:
TypeError: a bytes-like object is required, not 'str'

Signed-off-by: Rob Herring <robh@kernel.org>